### ISSUE TITLE
Start tagging versions

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#141]

**Comment by matsen** [comment]
Please tag, then release with a description of what was done: https://github.com/psathyrella/partis/releases
I suggest deleting this old release.

For extra credit, keep a CHANGELOG and then paste its contents into your release notes like [for pplacer](https://github.com/matsen/pplacer/releases/tag/v1.1.alpha15). If you use the magic GH-141 format, it will turn them into links.
