### ISSUE TITLE
How do we want to tell users to handle batch parallelization?

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#150]
If they have slurm, we may be able to get this to work from inside docker. But maybe not. And what if they use something besides slurm?

**Comment by matsen** [comment]
< 1% of users will use slurm. 

If you are serious about making it easy for folks to run partis in parallel, [Spark](http://spark.apache.org/docs/latest/programming-guide.html#tab_python_0) is the forward-thinking way to go.

**Comment by psathyrella** [comment]
`< 1% of users will use slurm`

Meaning they'll use some other batch system? I'm only bringing this up because jakub just tried to run on enough sequences that my heuristics n_proc decider decided he needed more processes than he had processors on his machine. I would love to not deal with it, but if I want to claim partis is useful for deep sequencing data sets I kinda have to get it working for other people on multiple machines?

**Comment by matsen** [comment]
Yes, slurm is quite rare in the life sciences. Setting something up for PBS would be more logical.

However, I do think that Spark is here to stay and that computationally expensive life science programs will be migrating there. 

Do you know what Jakub would want if he was to try to parallelize his jobs?

**Comment by jotwin** [comment]
We have access to a slurm setup, but I've never used it and I'd like to avoid it unless its really necessary. 
It probably doesn't meet your needs, but I use gnu parallel to do trivial parallelization.
 https://www.gnu.org/software/parallel/
It can ssh to machines, send files, run commands, and retrieve results.

**Comment by psathyrella** [comment]
The parallelization we're using is pretty trivial -- on one machine, it's just subprocess.Popen(cmd.split()), and for multiple machines we just tack 'srun' on the front of the command string. So it would actually be very easy to accommodate any parallel framework that just needs something tacked onto the command line.

If that's the case for gnu parallel I could add it now, but we just got comments back on the paper so I probably won't implement the final solution for a month or so. The final solution will, probably, be having folks run on an AWS instance.

**Comment by matsen** [comment]
@jotwin I'm a big fan of parallel, though I don't think that it's a good fit here because partis needs to be able to take in the data, reason about it, and then spin off the jobs. Thus we would be having partis calling parallel, which would seem strange because Python can already send off subprocesses.

To be clear, is your use case many processes on one machine, or on some number? 

Also (survey question) if we had a nice AWS solution would that suit you?

**Comment by jotwin** [comment]
I use gnu parallel for making use of 30 processors over 3 machines. Right now I'm trying to use partis on a single 12 (real) core machine with 24 GB memory, but partis is running out of memory on my big data set (new topic?).

I don't think we could pay for AWS because our institutions are begging us to use their underused and overly complicated computing resources. We can even use slurm for that.

**Comment by psathyrella** [comment]
Yeah, the memory is separate from parallelization. There's a master python process that reads input info, and then sends out a buncha jobs at each step, reads the results, and sends out more jobs. This master process a.t.m. just keeps all the input info, and the clustering info for each step in memory. There's a ton of ways I can optimize this by cacheing things to disc or keeping track of fewer things, I just haven't spent that much time running on million-plus data sets, and when I do we have a few machines with totally obscene amounts of memory (#151).

If it's just a matter of getting started with slurm, I can say from recent experience it's very easy if one ignores all the superfluous doodads. I mostly just add 'srun' in front of my command lines. In terms of partis, it's a matter of adding --slurm, and setting --workdir to something that's visible to all the batch nodes (by default, the workdir's set to /tmp/$USER/hmms/$RANDOM/, and when I'm slurming I replace /tmp with a network'd filesystem that's more heavy duty than our /home).

**Comment by psathyrella** [comment]
subsuming into #164
