### ISSUE TITLE
handle paired heavy and light chain data

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#153]

**Comment by matsen** [comment]
edited to reflect what you meant.

**Comment by psathyrella** [comment]
hahaah... no, I actually thought paired end was what you meant. There's already an IGL issue, #34, but I'll split that out to be just TCR.

**Comment by matsen** [comment]
No, this is not just IGL, it's _paired_ IGL and IGH.

**Comment by krdav** [comment]
Has this been implemented? It is of great interest to me to be able to use partis for both heavy and light chain annotation. 

Even better, when light chain annotation is implemented then partitioning of VL should also be rather simple to add. In the end using coupled VL and VH sequences to validate the partitions would also be very interesting, adding biological data to the simulation studies, as support for using likelihood based partitioning.

**Comment by psathyrella** [comment]
Not yet! But we agree it'll be super useful. I'm mostly working on getting germline sets correct, and I think this'll be the next thing, so perhaps a month or two? Always hard to know how hard it'll be until we start.

**Comment by psathyrella** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/partis/efTRw2b4Z9M/WDVTGxutBgAJ

**Comment by matsen** [comment]
Wanted to record that [receptor editing](http://www.nature.com/nri/journal/v6/n10/full/nri1939.html), in which there is subsequent rearrangement of the light chain, will make this a little more tricky. As D pointed out today, this could make the same clonal lineage appear to be multiple lineages, and perhaps we could do something later than would explicitly consider editing to bring these back together.

**Comment by psathyrella** [comment]
adding notes from discussion with kristian:

if it's true that:
  - single-chain partition paths are inaccurate only in that they're not sure where they should have stopped, and not that they went down a wildly wrong clustering path (which is a very good assumption)
  - the vast majority of the clustering information from light chain is just the kv and kj choice (very good assumption, since mean number of nucleotides in light chain not from v or j is about 1 [it's about 20 for heavy chain]

then we can get almost all the benefit of the ideal paired clustering (i.e. passing likelihood information "between" the heavy and light clustering paths in real-time, which would be very time-consuming to implement) by just looking at the final heavy chain clustering path and using the light chain kv/kj choice, in addition to just the heavy chain partition likelihood, to decide which partition is the most likely.

**Comment by psathyrella** [comment]
Paired heavy and light simulation is now implemented: https://github.com/psathyrella/partis/blob/dev/docs/subcommands.md#paired-heavy-and-light-chains.

**Comment by Zhemm** [comment]
Hello Everyone,

I’m looking for a large database for heavy chain and light chain of antibodies. Does anybody has any suggestions?

**Comment by psathyrella** [comment]
Not quite sure if you're meaning that you need them actually paired, or if just having heavy and light is enough. There's a lot of public samples listed on the b-t.cr wiki [here](https://b-t.cr/t/publicly-available-airr-seq-data-sets-b-cells/470) and [here](https://b-t.cr/t/publicly-available-airr-seq-data-sets-b-cells-continued/525). I think some of those are paired if you ctrl-F?. The real data i have to validate the paired clustering that i'm working on isn't public, but if simulation works for you, you can make as large of samples as you want with the partis paired h/l simulation (scroll down a bit from [here](https://github.com/psathyrella/partis/blob/dev/docs/subcommands.md#simulate) to get to the paired simulation example command: `partis simulate --parameter-dir _output/_path_to_sample --outfname simu.yaml --n-sim-events 3 --debug 1`).
