### ISSUE TITLE
Don't run multi HMM on all the seqs in a big cluster

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#162]
When we've got a really big cluster, like more than 20 sequences, it's probably really wasteful to compare to other clusters using *all* the sequences in the cluster. We could pick just a few representative ones, maybe.

This is basically the same as the naive hfrac code for large clusters.

**Comment by matsen** [comment]
First, what is the "objective function" to use for evaluating such an approximation? I suggest that the approximation should keep the same rank order of the likelihood ratios for surrounding clusters as the full likelihood ratio. 

I think that uniform sampling of the sequences in a cluster could work well. However, I think that a little bit of effort towards proportional representation across the hierarchical tree would be better. For example, you could imagine a recursive sampling scheme going down the tree such that if we want to sample k sequences and are at an internal node such that the two subtrees at that internal node have r and s descendants, that you sample kr/(r+s) and ks/(r+s) from each of the two subtrees. (I'd suggest rounding up the count from the smaller subtree when things don't divide cleanly.)

But, do you keep track of the sequence of merges?

**Comment by psathyrella** [comment]
I was thinking to use the same metrics as we're already using, mostly precision and sensitivity, but the order could be useful too.

Yeah, I definitely agree we can do better than random sampling. We'll need the simple way as a baseline, anyway, though, so I'll do it that way first.

Not explicitly, but it's trivial to keep track or not within a given process. But as with most everything, the paralelization introduces large complications.

for future reference:
http://sysbio.oxfordjournals.org/content/62/6/824
http://www.genetics.org/content/201/2/499.full

**Comment by matsen** [comment]
DK-- just a reminder that we don't have to keep the sequence of merges in order to do some sort of proportional sampling if we decide on the number of representative sequences in advance. All that's needed is to keep the actual sampled sequences and the number of sequences that would have been there if we had kept them all. 

That way, when we merge two cluster, we combine the sequence sets and apply some random sampling, which is biased by the number of sequences that would have been in each cluster.

**Comment by matsen** [comment]
This is tabled until we understand if it can actually make things faster.

**Comment by psathyrella** [comment]
I'm going to close this because even the simple way didn't help very much (maybe not at all). Well, I think it does in certain circumstances, so it's worth having in for certain repertoire structures, but real-world, overall, computation time just doesn't scale as proportionally with number of sequences as one would expect (probably mostly because of chunk caching).
