### ISSUE TITLE
Ghost states?

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#166]
i.e. non-emitting states between regions to reduce the number of transitions (p. 3 of http://arxiv.org/pdf/1511.00107v1.pdf). I know we thought about these at some point, and totally don't remember exactly, but I think I didn't use them because stochhmm couldn't handle non-emitting states. But then I rewrote stochmm, so maybe they make sense now? Or hell maybe we already have them in there! I don't remember! Maybe worth checking though.

**Comment by matsen** [comment]
I think that we already do better than this with factorization.
