### ISSUE TITLE
Minimize number of states in each loop

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#168]
i.e. in trellis::Viterbi/Forward see if we can reduce the number of times we go through the loops.

This may or may not be equivalent to the pre-alignment they talk about in the repgenhmm paper (i.e. assuming each position in the sequence can only be a certain state in the V or J)

**Comment by matsen** [comment]
All of our time is spent calculating the DP table. Main gain has been avoiding calculating it. 

This issue concerns speeding calculation of DP table. 

E says: loop unrolling?

**Comment by psathyrella** [comment]
Looks like the gcc option `-Ofast` is, among many other things, unrolling loops that it deems useful.

**Comment by matsen** [comment]
Yes, though it can only fully unroll loops if the number of iterations is fixed at compile time.

**Comment by psathyrella** [comment]
huh, this is still open... well I spent a bunch of time optimizing/caching for the loops a month or so ago. There's always more to do, but I don't need this open any more.
