### ISSUE TITLE
Implicit info warnings

### ISSUE THREAD

**Issue by Irrationone** [psathyrella/partis#177]
Hello,

Thanks for designing partis! I've been trying it out and I'm not sure what to make of these types of warnings:

```
./bin/partis.py --action cache-parameters --seqfile test.fastq --n-procs 1 --is-data --parameter-dir <out_dir>
  NOTE --is-data is no longer needed (it's the default; add --is-simu if running on simulation)
   adding placeholder alignments for missing genes j1P01 j2P01 j3P01 j3P02
smith-waterman
        processed       remaining      new-indels          rerun: unproductive      no-match      weird-annot.      nonsense-bounds      invalid-codon
             1               1              0                           0               1               0               0               0             increasing mismatch score (1 --> 2) and rerunning them
             1               1              1                           0               0               0               0               0             rerunning for indels
             1               1              0                           0               1               0               0               0             increasing mismatch score (2 --> 3) and rerunning them
  WARNING pre-existing info -115 doesn't match new info -86 for cdr3_length in <removed_id>
  WARNING pre-existing info 119 doesn't match new info 148 for tryp_position in <removed_id>
  WARNING pre-existing info G doesn't match new info C for d_qr_seq in <removed_id>
  WARNING pre-existing info TCCCCTGGTGGCAGATAACGCAGCTACTCGAGTC doesn't match new info GAGTCTCCCAGTCGCCCAGACACAAGATCAGAAA for j_qr_seq in <removed_id>
```

`test.fastq` contains one entry:

```
@<removed_id>
CTGGCAGTGGTATCAACGCAGAGTACGGGGCTCACAGTGACCCTGATCTGGTAAAGCTTCCATCCTGCCCTGTCCCTGCCATGGGCACCTGCCTCCTCTGCTCGTTGGCCCTGTGTCCCCTGGTGGCAGATAACGCAGCTACTCGAGTCTCCCAGTCGCCCAGACACAAGATCAGAAAGAGGGGCCCGAATGTAACCTTCAGGTCTGCTCCAATTTCTCAACACAACCGCCTTTCATGTAATGGACAGACC
+
DDDDDIIIIIIIIIIIIIIIIIIIIIIIII//11<11<11<1<FH11D<F1F1<11111<1111<G1G11<<1<11<1C111111<1D11<11<<D1111<110/111<1D11<1111<11<11<0110111<1<?/C/D11<0<<000<0<@0<////<<EH/<//<@G#################################################################################
```

Should they be ignored?

**Comment by psathyrella** [comment]
Thanks for trying it out!

Yeah, you can ignore them. I removed the warnings in the dev version, which'll get merged into production soon. They *are* a sign that it's not a particularly straightforward sequence to annotate, hence it gets different answers when it does things in different ways, but that's fine, and it's only in the preliminary smith-waterman step, anyway.

And forgive me if you already know, but if you're actually caching parameters you'll want to do it with more than one sequence...

**Comment by Irrationone** [comment]
Ahh, ok. I isolated the sequence since it seemed to be causing the problems -- definitely not planning on running it that way!

Also, what is the recommended strategy for inputting two paired-end sequence files to partis? Should each pair of reads be merged, or does it suffice to append two paired-end files into one single fasta/q file?

**Comment by psathyrella** [comment]
We don't explicitly handle paired-end reads yet, so if you can merge them before hand (e.g. with presto) that's best.

**Comment by matsen** [comment]
> And forgive me if you already know, but if you're actually caching parameters you'll want to do it with more than one sequence...

Perhaps we could make this more clear in the manual? It's in the papers, but it'd still be nice to have in the manual as well.

**Comment by psathyrella** [comment]
Done.
