### ISSUE TITLE
turn --actions into subparsers

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#181]
as suggested by Namita (thanks!)

```consider making the --action options into subparsers in the argparse library. With each subparser, you can then specify the specific parameters relevant to that action. If there are parameters shared by all, that can be placed into a parent parser that each subparser adopts.```

**Comment by matsen** [comment]
👍 

If you want an example, this is done nicely in seqmagick [here](https://github.com/fhcrc/seqmagick/blob/master/seqmagick/scripts/cli.py), in which we don't actually require a flag for the --action verb. It's like `git commit`, etc.

**Comment by psathyrella** [comment]
done.
