### ISSUE TITLE
package import paths

### ISSUE THREAD

**Issue by namita1025** [psathyrella/partis#183]
I noticed that if I try to run partis while not in the directory, it complains about finding packages it needs to import. Are the paths to these hard-coded to be relative to current working directory? Is there a way to change that?

**Comment by psathyrella** [comment]
yeah, in effect. The imports assume are handled with `sys.path.insert(1, './python')`. I'll poke around to see what's the best way to do that. All I remember is I didn't like how was handled in a lot of cases, but clearly you should be able to run anywhere you like.

In the meantime, though, you can add `export PYTHONPATH=/path/to/partis/python` to your env.
