### ISSUE TITLE
remove boost dependency

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#191]
as seen here https://github.com/jbeder/yaml-cpp/pull/342

**Comment by matsen** [comment]
Let me know when this is done so I can remove boost from our Docker image, please!

**Comment by psathyrella** [comment]
yeah, don't worry, I'll remove boost from the docker file as well.

I actually tried to do this a month or two ago, but they've rearranged the yaml-cpp code base, so I couldn't just drop in the new version, and it was going to take longer than the time I had budgeted at the time.

**Comment by psathyrella** [comment]
this will also be nice because compiling on 16.04 starts throwing deprecation warnings for all the smart pointer stuff in yaml-cpp
