### ISSUE TITLE
Allow to use annotation output file as input for partitioning

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#196]
Just need to make sure the annotation output and partition cache file formats are compatible, otherwise the infrastructure's there in `--persistent-cachefname`.

**Comment by krdav** [comment]
Yeah that is a good one! The vsearch run would then take no time.

**Comment by psathyrella** [comment]
note to self: integrate this with #154 and `--only-smith-waterman`.

**Comment by psathyrella** [comment]
Spent some time on this last week. It'll be a little more involved than I thought, so unless there's squawking I'm finishing light chains first.

**Comment by krdav** [comment]
I could add to this that it would also be great if there would be an option to print the annotations when running clustering. This should probably be an easy thing to implement.

**Comment by psathyrella** [comment]
There totally is! There's an option to print ASCII art annotations
(--print-cluster-annotations I think. Better with dark bkg). I think it
doesn't write them to csv by default, although it passes them around
internally as CSV.

**Comment by krdav** [comment]
Thank you, I will try that.

**Comment by psathyrella** [comment]
This was added a while ago.
