### ISSUE TITLE
Add non-human flag

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#204]
prolly only add mouse to start with

**Comment by matsen** [comment]
Just out of curiosity, what would this do?

I assume you saw

![](http://btcr.s3-us-west-2.amazonaws.com/original/1X/52fc27717d4dbb2767dfb901fcfd43dcbff08c2a.png)

**Comment by psathyrella** [comment]
uh, let people run partis on non-human data?

**Comment by matsen** [comment]
:) I get that part, but what's different about non-human data besides specifying the class (where class is IgK, IgH, etc).

**Comment by psathyrella** [comment]
As far as I know, yes, all I need to do is add more germline sets. But I also need to test it, and I won't be surprised if something else comes up...

**Comment by matsen** [comment]
Definitely.

👍

**Comment by psathyrella** [comment]
added Mus.
