### ISSUE TITLE
Option of both lambda and kappa option for light chain annotation

### ISSUE THREAD

**Issue by krdav** [psathyrella/partis#209]
Currently partis gives the option of either lambda or kappa light chain. A good addition to that would be to add the option of both using lambda and kappa germlines for sw align and pick the best match. In many applications presumably you will not know the origin of the light chain germline before hand, and most times samples will contain both lambda and kappa VL sequences. Hence, in those cases it makes most sense to let partis decide on the fly which germline to choose from.

**Comment by psathyrella** [comment]
if possible, when implementing this I should make it more difficult to have a mismatch between the germline gene chain and the `--chain` argument (see #214).

**Comment by krdav** [comment]
Option is now there and it is working nicely.
