### ISSUE TITLE
Support TCRs

### ISSUE THREAD

**Issue by laserson** [psathyrella/partis#228]
Would it be possible to add germline info for TCRs? Is there a reason that partis won't work for TCRs?

**Comment by psathyrella** [comment]
No, I don't think so. We just never got around to it since without shm everything's so much easier. But I guess there's always sequencing error, and it should be super easy. I'll get on it.

**Comment by psathyrella** [comment]
upon further investigation, this looks like it'll take a little more than just downloading some files from imgt, so it'll probably take a week or two to get to. Let me know if you have a deadline, though.

**Comment by laserson** [comment]
One or two weeks should be fine.  Thanks for doing it!

**Comment by psathyrella** [comment]
ok, I think this is working properly. Let me know if you run into any problems. In case you're not on the [google group](https://groups.google.com/forum/#!forum/partis), I wrote a few notes on the implementation.

**Comment by laserson** [comment]
Thanks for taking care of this so quickly btw!  I'm gonna close the issue.

**Comment by psathyrella** [comment]
rad, so it really works! wooooooooooooo!
