### ISSUE TITLE
Integrate cluster size/number options

### ISSUE THREAD

**Issue by metasoarous** [psathyrella/partis#239]
Not sure what the option would be called, but perhaps something like `--min-cluster-size`?

This comes from https://github.com/matsengrp/cft/issues/183 (private repo, atm).

**Comment by psathyrella** [comment]
i.e. --n-final-clusters, --max-cluster-size, --small-clusters-to-ignore, --n-steps-after-which-to[...]

such that we can tell it to ignore --n-final-clusters if some of the clusters are pretty big.

**Comment by psathyrella** [comment]
see new (well, since july 2017) --min-largest-cluster-size option (already used in input that cft gets).
