### ISSUE TITLE
Simulation section of the manual could use some love

### ISSUE THREAD

**Issue by matsen** [psathyrella/partis#240]
Some little formatting issues here:

![screenshot 2017-10-08 at 7 45 33 am](https://user-images.githubusercontent.com/112708/31317825-cadfe812-abfc-11e7-9328-2f91849330cd.png)

and a little more detail would help in general. For example, the Weibull parameter doesn't make sense without a link to http://dx.doi.org/10.1093/sysbio/syv001

**Comment by psathyrella** [comment]
Yeah, thanks for noticing. This is definitely on the todo list for the paper.
