### ISSUE TITLE
installation issues and problem with waterer.py

### ISSUE THREAD

**Issue by Pezhvuk** [psathyrella/partis#244]
Hi,

I have been attempting to install sumrep and partis from scratch and ran into quite a few dependencies issues. I could list these issues which maybe helpful if added to the installation guide.

Now that Partis is installed, I'm running into an issue when running the quick start command. The issue is with the waterer.py script and I receive the following key attribute error:

`AttributeError: 'csamtools.AlignedRead' object has no attribute 'cigarstring'`

And here is the whole output:

`parameter dir '_output/_home_pejvak_partis_test_example' does not exist, so caching a new set of parameters before running action 'annotate'
caching parameters
vsearch: 250 / 250 v annotations (0 failed) in 0.1 sec
    keeping 20 / 239 v genes
smith-waterman 
         step  seqs    procs     ig-sw time    processing time
           1    250      1  Traceback (most recent call last):
  File "./bin/partis", line 627, in <module>
    args.func(args)
  File "./bin/partis", line 189, in run_partitiondriver
    parter.cache_parameters()
  File "/home/pejvak/partis/python/partitiondriver.py", line 260, in cache_parameters
    self.find_new_alleles()
  File "/home/pejvak/partis/python/partitiondriver.py", line 189, in find_new_alleles
    self.run_waterer()
  File "/home/pejvak/partis/python/partitiondriver.py", line 170, in run_waterer
    waterer.run(cachefname if write_cachefile else None)
  File "/home/pejvak/partis/python/waterer.py", line 89, in run
    self.read_output(base_outfname, n_procs)
  File "/home/pejvak/partis/python/waterer.py", line 377, in read_output
    qinfo = self.read_query(sam.references, readlist)
  File "/home/pejvak/partis/python/waterer.py", line 521, in read_query
    if 'I' in read.cigarstring or 'D' in read.cigarstring:  # shm indels!
AttributeError: 'csamtools.AlignedRead' object has no attribute 'cigarstring'
       1.5     
Traceback (most recent call last):
  File "./bin/partis", line 627, in <module>
    args.func(args)
  File "./bin/partis", line 202, in run_partitiondriver
    check_call(newargv)
  File "/home/pejvak/anaconda3/envs/partis/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['./bin/partis', 'cache-parameters', '--infname', '/home/pejvak/partis/test/example.fa']' returned non-zero exit status 1`

I would appreciate any help with this.
Cheers,
Pej.

**Comment by psathyrella** [comment]
That looks like it's probably a version issue with pysam -- presumably they didn't used to have the cigar string as a member.  `pysam.__version__` on my machine gives 0.10.0, which works.

**Comment by BrandenOlson** [comment]
@Pezhvuk Would you mind posting an issue in `sumrep` about the dependency issues you had during installation?

**Comment by dunleavy005** [comment]
FYI @BrandenOlson , Kristian and I ran into a similar issue with pysam b/c default conda pysam doesn't have a recent enough version. Doing `conda update -y -c bioconda pysam` after the normal partis conda install fixed it for me.

**Comment by BrandenOlson** [comment]
@dunleavy005 I see, thank you for letting me know! I'll add a note to the README.

**Comment by Pezhvuk** [comment]
Hi @Branden,

Sure I'll put the list together before the Monday meeting. I wish I had kept a proper note at the time, but I was rushing to get it to work so I could do some analysis before Monday. Though I remember some of them.

**Comment by Pezhvuk** [comment]
hi @psathyrella and @dunleavy005,

I tried `conda update -y -c bioconda pysam`, but I'm still getting the exact same error.

**Comment by psathyrella** [comment]
I don't think I follow the particulars of whether your conda install is broken or not, but since we seem to have established that updating pysam will fix the problem, you can check that by starting python from the command line and running

```
import pysam
print pysam.__version__
```

**Comment by psathyrella** [comment]
oh, and I meant to add -- using the docker installation instructions would require less familiarity with the underlying operating system, so might prove easier.

**Comment by Pezhvuk** [comment]
update:
`conda update -y -c bioconda pysam` does work, but this has to be done within the source activated environment (SAE), which wasn't so obvious to me, as this was my first time working with SAE.
The reason I was receiving the error on my latest post, i.e. conda install/update being broken, was due to a troubleshooting I had to do to resolve an issue with the following part of the installation:
`R --vanilla --slave -e 'install.packages("TreeSim", repos="http://cran.rstudio.com/")'`.
I was getting a non-zero exit status for most of the dependencies of TreeSim, which complained that I was missing x86_64-conda_cos6-linux-gnu-cc directory and other errors that had to be resolved by installing the following modules through conda: gxx_linux-64 and gfortran_linux-64.
These, however, would break the conda install/update within SAE for some reason, which prohibits further installations/updates through conda. Moreover, you have to install them both in the same line, as each one of them has that effect.
Once I ran the example code, I ran into another issue, which was that yaml module does not exist in SAE conda by default. naturally I had to redo everything all over again and install yaml before the gxx_linux-64 and gfortran_linux-64.
I finally ran partis successfully. So, happy ending.

**Comment by psathyrella** [comment]
OK, thanks for the feedback. As far as we can tell, those compilers and pyyaml are properly installed when things are done all at once and in order (for example [this](https://github.com/krdav/SPURF/blob/master/INSTALL)  has been tested a lot) but I'm glad you got it working.

**Comment by michael-swift** [comment]
Hi all, 

Thanks for creating this tool psathyrella! I get this same issue when running the latest docker image from here (https://hub.docker.com/r/matsen/partis/tags). I'm wondering if it would be possible to update the docker image that has been pushed to Dockerhub? Is this the correct docker image or is there a more up to data one? Thanks!

**Comment by psathyrella** [comment]
Ah, no! Sorry, we [switched to quay.io](https://github.com/psathyrella/partis/blob/dev/docs/install.md#installation-with-docker) since docker hub started being unusable on free tier. lmk if you run into more problems.

**Comment by michael-swift** [comment]
awesome found it thx!
