### ISSUE TITLE
Simulate functional repertoire only

### ISSUE THREAD

**Issue by scharch** [psathyrella/partis#248]
I am seeing a lot of stop codons generated, both in CDR3 by the simulated recombination and in V by simulated SHM. At the moment, I am only interested in the functional repertoire, though, so it would be nice to be able to tell partis to consider those sequences invalid.

**Comment by psathyrella** [comment]
Yes, this should be an option. It'll just involve throwing out a bunch of sequences (like half of them I think? stop codon combinatorics kind of suck) after the fact, since bppseqgen isn't going to know about stop codons.

quick fix: add ` + tuple(functional_columns) ` to the end of [this](https://github.com/psathyrella/partis/blob/dev/python/utils.py#L291) line, and then the `stops` column will be added and you can grep on it or whatever.

**Comment by scharch** [comment]
It's not relevant to my current use case, but wouldn't just throwing them out post hoc mess up your tree statistics for simulating the clonal structure of a repertoire?

**Comment by psathyrella** [comment]
yep :(

I'd probably just have to keep rerunning the bppseqgen step until it gives me something with no stop codons... but for large families that will be never. So maybe just revert the stop codons? This is how I deal with mutated cyst/tryp/phen invariant codons, but they're much less common, and there's already an issue to stop doing it that way. Reverting all stop codons would probably screw up the shm characteristics too much.

So the answer might be that if you specify only functional sequences, you'll only get a fraction of the original tree -- which is biologically what's happening, so also the cleanest to code up.

**Comment by scharch** [comment]
> you'll only get a fraction of the original tree -- which is biologically what's happening

Depends how you think about this. If the tree parameters are learned from the functional repertoire (ie those that have already survived selection) then I don't think that logic applies. OTOH, I don't have a better solution, at the moment....

**Comment by psathyrella** [comment]
Well, once I start learning clonal family properties from data and propagating to simulation... but partis doesn't do any of that yet.
