### ISSUE TITLE
correct/update version information

### ISSUE THREAD

**Issue by scharch** [psathyrella/partis#271]
```
schrammca@cogsworth:/home/schrammca/partis/partis$ bin/partis version
RUN bin/partis version
       tag v0.9.0
    commit 00421b4158455e924d0a610ca0015c22465f4681
schrammca@cogsworth:/home/schrammca/partis/partis$* git describe
v0.1.0-4179-g00421b4
```
...but both appear to be wrong, as the current version tag is 0.14.0 according to github

**Comment by psathyrella** [comment]
oops, darn, nice catch. I was just running `git tag` and taking the [last](https://github.com/psathyrella/partis/blob/master/python/processargs.py#L79) line. Which is foolish, as that isn't how it's sorted. And darn it, I just noticed that all previous tags had a `v` in front, but I forgot it last time. Oh well too late.

I'll figure out what command I should be running and close.

**Comment by scharch** [comment]
For SONAR, I use `git describe --always --tags`
