### ISSUE TITLE
Sequences marked as unproductive for unknown reasons 

### ISSUE THREAD

**Issue by nannabarnkob** [psathyrella/partis#279]
Hi,
We are having troubles understanding why our sequences are marked as unproductive. The antibody sequences have been validated experimentally and Sanger sequenced to ensure they are certainly productive. Approximately 10% of our sequences are annotated to be unproductive. We have tried to solve the problem by running on the subset of heavy chain sequences (49 sequences) that we 'lose'. We are using our own germline sets which we have attempted to set up like yours, which means that we have made the ighv.fasta, ighj.fasta ighd.fasta and extras.csv stating the cys, tryp and phen-positions. As the germline genes are selected by the model for many of the productive sequences, we are quite certain that the germline set is correctly formatted.   

We use the following command for running partis: 
```
partis partition --print-cluster-annotations --n-procs 24 --locus igh --initial-germline-dir /home/projects/cu_10049/apps/partis/data/germlines/germline --infname /home/projects/Partis_unproductive/missing_seqs_VH.fa --outfname /home/projects/Partis_unproductive/missing_seqs_VH_partition.csv --parameter-dir /home/projects/partis_params/missing_seqs_VH --workdir /tmp/partis/41111 --leave-default-germline
```

We get the following output: 
```partitioning
smith-waterman
  vsearch: 49 / 49 v annotations (0 failed) with 10 v genes in 0.1 sec
    running 24 procs for 49 seqs
    running 24 procs for 1 seq
      info for 49 / 49 = 1.000   (0 failed)
      kept 49 (1.000) unproductive
      removed 1 / 49 = 0.02 duplicate sequences after trimming framework insertions (leaving 48)
    water time: 0.3  (ig-sw 0.0  processing 0.1)
hmm
caching all 48 naive sequences
  warning no hmm files for glfo genes IGHD2-2*01 IGHV3-7* IGHD2-2*03 IGHD2-2*02 IGHD2-15*01 IGHD5-24*01 IGHD6-13*01 IGHD5-18*01 IGHJ6*04 IGHV3-73* IGHJ6*02 IGHJ6*03 IGHJ6*01 IGHD1-26*01 IGHD6-19*01 IGHV4-4* IGHD4-11*01 IGHV1-58* IGHV3-66* IGHV3-15* IGHV3-38* IGHD1-14*01 IGHD2-21*01 IGHV1-18* IGHD2-21*02 IGHV3-53* IGHV3-11* IGHV6-1* IGHV7-4* IGHJ3*02 IGHJ5*02 IGHJ5*01 IGHV2-70* IGHD6-25*01 IGHV3-48* IGHV3-43* IGHV5-51* IGHV3-30* IGHV1-46* IGHV1-8* IGHJ4*03 IGHD3-3*01 IGHV4-31* IGHD3-3*02 IGHD6-6*01 IGHJ4*01 IGHV3-20* IGHD1-7*01 IGHJ3*01 IGHV2-5* IGHD1-20*01 IGHD7-27*01 IGHV3-72* IGHD4-17*01 IGHD1-1*01 IGHV3-23* IGHV4-61* IGHV1-2* IGHV4-39* IGHV3-64* IGHD2-8*02 IGHD2-8*01 IGHV1-3* IGHV3-22-2* IGHV3-74* IGHV3-35* IGHD3-22*01 IGHV3-13* IGHJ1*01 IGHD5-12*01 IGHD3-10*01 IGHV1-45* IGHV4-34* IGHV3-21* IGHD3-10*02 IGHD3-16*02 IGHV2-26* IGHV1-69* IGHD3-16*01 IGHV4-59* IGHV1-24* IGHV3-49* IGHV4-28*
       no v genes in  for ['DNA=2XXX2_VH']
          skipped IGHD7-27*01:IGHV3-21*:IGHJ6*01:IGHD3-16*02:IGHJ6*02:IGHD1-26*01:IGHD5-12*01:IGHD3-10*01
giving up on query
       no v genes in IGHJ4*02 for ['DNA=XXX50_VH']
          skipped IGHD7-27*01:IGHD2-15*01:IGHD6-6*01:IGHJ4*01:IGHD5-12*01:IGHD6-13*01:IGHV3-13*:IGHV3-21*:IGHJ6*01:IGHD3-16*02:IGHJ6*02:IGHD1-26*01:IGHD6-19*01:IGHD6-25*01:IGHD3-10*01
```

In order to solve the problem, we ran partis using the debugging mode for Smith-Waterman alignment (`--sw-debug 2`) where we got the following output (some of the sequence has been substituted with N's for confidentiality) 

```
 note: --outfname uses deprecated file format .csv. This will still work fine, but the new default .yaml format is much cleaner, and includes annotations, partitions, and germline info in the same file.
partitioning
smith-waterman
  vsearch: 49 / 49 v annotations (0 failed) with 10 v genes in 0.1 sec
    added 3 vsearch indels (DNA=2XXX9_VH DNA=25XXX_VH DNA=2XXX4_VH)
    running 24 procs for 49 seqs
reading output
  DNA=2XXX6_VH
      rerun: new indels in v
  DNA=25XXX_VH
        hv3-13                      1350           0 292   AGGTGCANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAAGAACTCCTTGTATCTTCAAATGAACAGCCTGAGAGCCGGGGACACGGCTGTGTATTACTGTGCAAGAGA
                                                   0 292   AGGTGCANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTATTGGTACTGCTGATGACACATACTATCTAGGCTCCGTGAAGGGCCGATTCACCATCTCCAGAGAAAATGCCAAGAACTCCTTGTATCTTCAAATGAACAGCCTGCGAGCCGGGGACACAGCTGTGTATTACTGTGCAAGAGA
        hd6-1901                      85           0  19   GGGTATAGCAGTGGCTGGT
                                                 293 312   GGATATAGCAGTGGCTGGT
        hd6-1301                      65           0  19   GGGTATAGCAGCAGCTGGT
                                                 293 312   GGATATAGCAGTGGCTGGT
        hd6-2501                      60           0  16   GGGTATAGCAGCGGCT
                                                 293 309   GGATATAGCAGTGGCT
        hd2-1501                      55           0  15   AGGATATTGTAGTGG
                                                 292 307   AGGATATAGCAGTGG
        hd2-802                       45           0  15   AGGATATTGTACTGG
                                                 292 307   AGGATATAGCAGTGG
        hj402                        205           0  43   ACTACTTTGACNNNNNNNNNNAGGGAACCCTGGTCACCGTCTC
                                                 321 364   ACTACTTTGNNNNNNNNNNNCCAGGGAACCCTGGTCACAGTCTC
        hj401                        195           0  43   ACTACTTTNNNNNNNGCCAAGGAACCCTGGTCACCGTCTC
                                                 321 364   ACTACTTTGNNNNNNNNCAGGGAACCCTGGTCACAGTCTC
   k_v 292 [292-293)  k_d 20 [15-30)
```

where we got the following error message: 

```

Error in sys.excepthook:
Traceback (most recent call last):
  File "/services/tools/anaconda2/4.0.0/lib/python2.7/site-packages/colored_traceback/colored_traceback.py", line 27, in colorize_traceback
    tb_colored = pygments.highlight(tb_text, lexer, self.formatter)
  File "/services/tools/anaconda2/4.0.0/lib/python2.7/site-packages/colored_traceback/colored_traceback.py", line 32, in formatter
    colors = _get_term_color_support()
  File "/services/tools/anaconda2/4.0.0/lib/python2.7/site-packages/colored_traceback/colored_traceback.py", line 66, in _get_term_color_support
    curses.setupterm()
_curses.error: setupterm: could not find terminfo database

Original exception was:
Traceback (most recent call last):
  File "/services/tools/partis/0.14.0/bin/partis", line 403, in <module>
    args.func(args)
  File "/services/tools/partis/0.14.0/bin/partis", line 192, in run_partitiondriver
    parter.run(actions)
  File "/services/tools/partis/0.14.0/python/partitiondriver.py", line 104, in run
    self.action_fcns[tmpaction]()
  File "/services/tools/partis/0.14.0/python/partitiondriver.py", line 390, in partition
    cpath = self.cluster_with_bcrham()
  File "/services/tools/partis/0.14.0/python/partitiondriver.py", line 579, in cluster_with_bcrham
    cpath, initial_nseqs = self.get_initial_cpath(n_procs)
  File "/services/tools/partis/0.14.0/python/partitiondriver.py", line 568, in get_initial_cpath
    initial_nsets = utils.collapse_naive_seqs(self.synth_sw_info(self.sw_info['queries']), split_by_cdr3=True, debug=True)
  File "/services/tools/partis/0.14.0/python/partitiondriver.py", line 561, in synth_sw_info
    synth_sw_info = {q : {'naive_seq' : s, 'cdr3_length' : self.sw_info[q]['cdr3_length']} for q, s in self.get_cached_hmm_naive_seqs(queries).items()}  # NOTE code duplication in cluster_with_bcrham()
  File "/services/tools/partis/0.14.0/python/partitiondriver.py", line 705, in get_cached_hmm_naive_seqs
    raise Exception('error above')
Exception: error above
```

Can you help elucidate what the problem is here?  

Thank you very much for your help. 
Best regards 
Clara and Nanna

**Comment by psathyrella** [comment]
It looks like you're doing everything right. There are three constituent columns that go into being marked productive: in_frames, stops, mutated_invariants (sorry on mobile so not linking to descriptions). Setting debug is indeed the easiest way to see which it is (although setting to 1 is probably better for your case than 2). I'm not sure what's causing that curses/term error, but maybe it's that you're not on a login terminal? I'll Google when I get on a laptop. But in any case the 49 unproductive should still be written to output file, so you can look at the three constituent boolean columns.

Wild guess, but if the v/codon positions were off that would cause it to think the cdr3 was out of frame, and I need to write docs for setting up your own germline sets (which you seem to have figured out pretty well) but for instance the positions have to be zero-indexed, which might catch you by surprise.

**Comment by psathyrella** [comment]
ok reading more carefully, this is interesting:

`no v genes in  for ['DNA=2XXX2_VH']`
`no v genes in IGHJ4*02 for ['DNA=XXX50_VH']`

This is from the code that takes the s-w matches and curates them into a format that'll make sense to the hmm, and it's saying that for the first sequence, the list of gene matches didn't have any v genes (and was actually empty). The second one also has no v genes, in a list of just one j gene. Which suggests that there could possibly be a mismatch between the --parameter-dir you're specifying, and these 49 queries. For instance, maybe the parameter dir was inferred on somewhat different sequences, with different genes, so the genes for these sequences aren't in the set. Also/similarly, it typically only makes sense to specify --initial-germline-dir during the 'cache-parameters' action -- this will use that germline set to infer a parameter dir, and then subsequent annotation/partition runs on that parameter dir will use that germline set.

So I'm guessing, since I don't know what command was used to make the parameter dir here, but I'd suggest trying something like:

```
partis cache-parameters --locus igh --initial-germline-dir /home/projects/cu_10049/apps/partis/data/germlines/germline --infname /home/projects/Partis_unproductive/missing_seqs_VH.fa  --parameter-dir /home/projects/partis_params/missing_seqs_VH --workdir /tmp/partis/41111 --leave-default-germline
partis partition --print-cluster-annotations --locus igh --infname /home/projects/Partis_unproductive/missing_seqs_VH.fa --outfname /home/projects/Partis_unproductive/missing_seqs_VH_partition.csv --parameter-dir /home/projects/partis_params/missing_seqs_VH --workdir /tmp/partis/41111
```

although maybe you want to use a different parameter dir, to avoid annihilating the one you're already using, that was inferred previously.

**Comment by psathyrella** [comment]
To clarify that ^ a little: in the manual we mostly describe running annotation/partition actions as one step that automatically also runs cache-parameters. This is simpler, and is probably best in the vast majority of cases. But when running with more advanced options like your own germline sets, or especially when rerunning on subsets of sequences, it's probably safer/better to run cache-parameters and partition as separate steps. fwiw I actually essentially always run them separately as two steps.

As to the curses error that's preventing you from seeing the ascii art annotations, I don't think I've encountered it, but my search history says I have googled it before, it seems like it probably stems from TERM  and TERMINFO [not being set](https://stackoverflow.com/questions/9485699/setupterm-could-not-find-terminal-in-python-program-using-curses). Although without knowing what sort of system you're on I'm just guessing and it could be something further down the [results](https://www.google.com/search?client=ubuntu&channel=fs&source=hp&ei=M1iaXNejE4iw0wL_vaXwCg&q=_curses.error%3A+setupterm%3A+could+not+find+terminfo+database&btnK=Google+Search).

**Comment by nannabarnkob** [comment]
Thank you so much for your quick and thorough reply! About the germlines: we worked it out mostly by looking at your own files, but more information on this would be highly appreciated when we get a new germline set in the future. We were also unsure whether our problem was related to this or not, but it is a bit difficult to take apart. The indexing was a very good and probable idea. 

We initially started out by running `partis partition` on all the sequences and then running it again on the unproductive subset, so you're right the parameter dir must be inferred. It makes so much more sense now we understand the difference between turning the germlines into something that can be used in the hmm and the actual partitioning. 
I tried running with the two-step approach as you suggested, and we didn't have any errors! 
With the sequences kept in the *-cluster-annotations.csv-output we were able to see that partis finds a stop codon within our sequences, meaning that the the problem is most definitely outside partis. 
Thank you for the link to the TERM and TERMINFO, although this error have seemed to worked itself out after the first issue was solved. We are running it on our linux platform cluster and will include the lines somewhere in our .bash_profile for future similar bugs, if any.  

Once again, thank you for your help! 

Best regards, 
Clara and Nanna

**Comment by psathyrella** [comment]
yay! solving problems is fun.

I think [this](https://groups.google.com/forum/#!topic/partis/RWDgyoUEpu4) is the best description of custom germline stuff I've written, although there might be another since I feel like I've written it several times, which means I should've put it in the manual a while ago.

**Comment by nannabarnkob** [comment]
Yes, we were by that thread as well for setting it up, luckily it wasn't too hard to find. 
Thanks again!
