### ISSUE TITLE
Investigate diversity of sequences used to train parameters

### ISSUE THREAD

**Issue by matsen** [psathyrella/partis#28]
Following 12/17 discussion with Vladimir. 

The issue is that the size of clonally related groups can impact individual-level inferences. For example, if 80% of sequences come from one clonally related group then it the other 20% are more likely to follow that sequence's path through the HMM. 

We could look at pairwise distance plots (though those do seem to be fairly mysterious sometimes, as lots of things are getting compressed down to a single number, and multiplicity gets squared). Perhaps trees are better, as long as we don't over-interpret them.

**Comment by psathyrella** [comment]
pretty similar to #69
