### ISSUE TITLE
No partition in the output 

### ISSUE THREAD

**Issue by NikaAb** [psathyrella/partis#284]
Dear Duncan, 

I have run partis on some of my fasta files, coming from CLL patients. In the output dictionary, the partition list is empty, I wonder if I use the right command.

This is how I run the partis :

`(base) root@8788e7f742a7:/partis/bin# ./partis annotate --infname /host/home/patients/P5.fa --outfname /host/home/P5_partis.yaml --n-procs 8
`

This is what I get :

`annotating
smith-waterman
  vsearch: 161985 / 162742 v annotations (757 failed) with 41 v genes in 37.2 sec
        reading sw results from _output/_host_home_patients_P5/sw-cache-7901971560392386892.yaml
      info for 161983 / 162742 = 0.995   (759 failed, 80553 duplicates)
      kept 22836 (0.140) unproductive
        water time: 39.8
hmm
    prepare_for_hmm: (8.6 sec)
    running 8 procs
                    calcd:         vtb  81430        fwd      0
             min-max time:  196.9 - 203.2 sec
    read output
        processed 81430 hmm output lines with 81407 sequences in 81407 events  (23 failures)
            warning skipped 15 invalid events
          warning no valid paths: S157058 S45210 S73099 S82197 S82809 S107180 S109301 S68536
         infra time: 91.8
      hmm step time: 335.8
      total time: 432.4
`

And this is what I have in the output dictionnary :

`>>> partis_output.keys()
dict_keys(['version-info', 'germline-info', 'events', 'partitions'])
`
`>>> partis_output['partitions']
[]
`

I looked also into the events, all the sequences are not invalide, I can't see where is the probleme. Do you have any idea ?
Thanks a lot !
Nika

**Comment by psathyrella** [comment]
Yes, you'll want to run `partition` to get clonal family clusters; `annotate` makes just annotations. See the descriptions [here](https://github.com/psathyrella/partis/blob/master/docs/subcommands.md).

**Comment by NikaAb** [comment]
Great, thanks! That was the first thing to verify, and I missed it!
