### ISSUE TITLE
get tree metrics for all partitions

### ISSUE THREAD

**Issue by sravani9408** [psathyrella/partis#297]
Hello Duncan,

I am interested in the Newick tree/annotation information for all the partitions (all including the best partition). I tried using --get-tree-metrics and --write-additional-cluster-annotations, but it does not return tree-info for the other partitions. 

Thanks

**Comment by psathyrella** [comment]
Oops, good point. I hadn't needed it, and was trying to minimize the number of trees we calculated. But it should be working as of [this](https://github.com/psathyrella/partis/commit/5b70f010c12a5e19b260d598c4e6b4241e57de50) commit, and I've also added a bit to the manual [describing](https://github.com/psathyrella/partis/blob/dev/docs/subcommands.md#--get-tree-metrics-and-get-tree-metrics-action) the provenance of the trees.

**Comment by sravani9408** [comment]
Thank you, Duncan.
