### ISSUE TITLE
Singularity

### ISSUE THREAD

**Issue by ashotmarg** [psathyrella/partis#328]
Hi @psathyrella ,

Thanks for the new Docker image/dockerfile for partis.

While things work fine with docker, I get a numpy error when I run singularity with the same docker image. That numpy issue is actually a more general python and conda related. After a bit of digging, it seems that when running with singularity the $PATH in the singularity container is different compared to the $PATH inside a docker container and doesn't include for some reason the "/opt/conda/" part.
I don't know why this is happening in case of singularity but if someone wants to run partis with singulraity a solution is:
`singularity exec --env PATH=/opt/conda/bin:/opt/conda/condabin:$PATH partis.sif ...`

To test things a bit more, I've added the following line in your dockerfile and rebuild the [image](https://hub.docker.com/layers/ashotmarg/partis/ash_v1/images/sha256-4b666c9858954260b298f3c415031cbb562071284618b19f9572e21b610811ad?context=repo), which seems to have solved the issue, when I run with singularity. But I haven't thoroughly tested things.

I've essentially added this line ("ENV PATH /opt/conda/bin:/opt/conda/condabin:$PATH") at the end of the dockerfile, right before the "CMD" statement, so the last two lines of the dockerfile looked like:
```
...
ENV PATH /opt/conda/bin:/opt/conda/condabin:$PATH
CMD ./test/test.py --quick
```

Please check this, and if it's fine, maybe it's worth updating the dockerfile/image so that the singularity can also run without the need of the extra "--env"  parameter.

**Comment by psathyrella** [comment]
OK just added this into main. Thank you for the suggested fix!
