### ISSUE TITLE
Different mutation rates to different bases: test new bio++ feature

### ISSUE THREAD

**Issue by psathyrella** [psathyrella/partis#87]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/biopp-devel-forum/cX-Q9aks7CA/mW1uQfCy-nUJ

**Comment by psathyrella** [comment]
erick's got it working

```stoat bpp/multimodel ‹master*› » bppseqgen param=multimodel.bpp > /dev/null && av sim.fa
```

**Comment by matsen** [comment]
A real CLI interface to come...

**Comment by psathyrella** [comment]
nice lil' bump for Kristian's point about amino acid substitution [here](https://groups.google.com/forum/#!topic/partis/rNSEjM3lf_Q)

**Comment by psathyrella** [comment]
I mostly implemented this last year, and just need to test it some more, so putting this here to remember: 

https://github.com/psathyrella/partis/blob/dev/bin/partis#L274
https://github.com/psathyrella/partis/blob/dev/bin/partis#L434

**Comment by psathyrella** [comment]
ha ha, yes! It took five years, but now that I have simulation with per-base mutation (i.e. at each position in each gene A->C has different probability than A->T), I can finally test how much difference having that in the inference hmm makes (it's always been in the inference hmm) Here I tell the hmm to ignore these differences with `--no-per-base-mfreqs` and the annotation accuracy indeed gets worse by a good bit.

![p](https://user-images.githubusercontent.com/2960243/82130558-486e8780-9781-11ea-9652-844973f92e82.png)
